import { Router } from "express";
import {
  createTicketTypeController,
  getTicketTypeByIdController,
  getTicketTypesByEventIdController,
  updateTicketTypeController,
  incrementTicketTypeSoldController,
  decrementTicketTypeSoldController,
  checkTicketTypeAvailabilityController,
  deleteTicketTypeController,
  getTotalTicketTypesCountByEventController,
  getTicketTypeWithEventController,
  getTotalRemainingTicketsByEventController,
  getTicketTypeRevenueController,
  bulkCreateTicketTypesController,
  getAvailableTicketTypesByEventController,
  isTicketTypeSoldOutController,
  updateTicketTypeCapacityController,
  getTotalEventTicketRevenueController,
  deleteAllTicketTypesByEventController,
  resetTicketTypeSoldController,
  updateTicketTypePriceController,
  cloneTicketTypesForEventController,
  getTicketTypesByPriceRangeController,
  validateTicketTypeBelongsToEventController,
  getEventTicketInventorySummaryController,
} from "./ticketType.controller";

import {
  adminAuth,
  adminOrOrganizerAuth,
  anyAuthenticatedUser,
} from "../../middleware/bearAuth"; // Adjust the path to your auth middleware file



const TicketTypeRouter = Router();

// ==========================================
// 🎟️ PUBLIC / GENERAL READ ROUTES (Any Authenticated User or Public)
// ==========================================

// 3. Get all ticket types for an event
TicketTypeRouter.get("/event/:eventId", getTicketTypesByEventIdController);

// 7. Check ticket type availability
TicketTypeRouter.get("/:id/availability",  checkTicketTypeAvailabilityController);

// 9. Count total ticket types by event
TicketTypeRouter.get("/event/:eventId/count",getTotalTicketTypesCountByEventController);

// 10. Get ticket type with event relation
TicketTypeRouter.get("/:id/with-event", anyAuthenticatedUser, getTicketTypeWithEventController);

// 11. Get total remaining tickets by event
TicketTypeRouter.get("/event/:eventId/remaining", anyAuthenticatedUser, getTotalRemainingTicketsByEventController);

// 14. Get available ticket types only (open & un-sold-out)
TicketTypeRouter.get("/event/:eventId/available", anyAuthenticatedUser, getAvailableTicketTypesByEventController);

// 15. Check if ticket type is sold out
TicketTypeRouter.get("/:id/sold-out", anyAuthenticatedUser, isTicketTypeSoldOutController);

// 22. Get ticket types by price range
TicketTypeRouter.get("/event/:eventId/price-range", anyAuthenticatedUser, getTicketTypesByPriceRangeController);

// 23. Validate ticket type belongs to event
TicketTypeRouter.get("/:id/validate-belonging", anyAuthenticatedUser, validateTicketTypeBelongsToEventController);

// 2. Get ticket type by ID (Keep parameter route below specific sub-routes to avoid conflicts)
TicketTypeRouter.get("/:id", anyAuthenticatedUser, getTicketTypeByIdController);


// ==========================================
// 🔒 ADMIN & ORGANIZER MANAGEMENT ROUTES (Restricted Actions)
// ==========================================

// 1. Create a single ticket type
TicketTypeRouter.post("/", adminOrOrganizerAuth,  createTicketTypeController);

// 13. Bulk create ticket types for an event
TicketTypeRouter.post("/bulk", adminOrOrganizerAuth, bulkCreateTicketTypesController);

// 21. Clone ticket types to a new event
TicketTypeRouter.post("/clone", adminOrOrganizerAuth, cloneTicketTypesForEventController);

// 4. Update ticket type details
TicketTypeRouter.put("/:id", adminOrOrganizerAuth, updateTicketTypeController);

// 16. Update ticket type capacity
TicketTypeRouter.patch("/:id/capacity", adminOrOrganizerAuth, updateTicketTypeCapacityController);

// 20. Update ticket type price
TicketTypeRouter.patch("/:id/price", adminOrOrganizerAuth, updateTicketTypePriceController);

// 8. Delete ticket type
TicketTypeRouter.delete("/:id", adminOrOrganizerAuth, deleteTicketTypeController);

// 18. Delete all ticket types for an event
TicketTypeRouter.delete("/event/:eventId", adminOrOrganizerAuth, deleteAllTicketTypesByEventController);


// ==========================================
// 📈 ANALYTICS & INTERNAL INVENTORY ROUTES (Admin / Organizer / Scanner)
// ==========================================

// 12. Calculate revenue generated by a specific ticket type
TicketTypeRouter.get("/:id/revenue", adminOrOrganizerAuth, getTicketTypeRevenueController);

// 17. Get total cumulative event ticket revenue
TicketTypeRouter.get("/event/:eventId/revenue", adminOrOrganizerAuth, getTotalEventTicketRevenueController);

// 24. Get comprehensive event inventory summary report
TicketTypeRouter.get("/event/:eventId/inventory-summary", adminOrOrganizerAuth, getEventTicketInventorySummaryController);


// ==========================================
// ⚡ INTERNAL SYSTEM MUTATION HOOKS (Protected for internal system / scanner services)
// ==========================================

// 5. Increment tickets sold count (triggered upon successful booking/payment)
TicketTypeRouter.patch("/:id/increment-sold", adminOrOrganizerAuth, incrementTicketTypeSoldController);

// 6. Decrement tickets sold count (triggered upon booking cancellation/refund)
TicketTypeRouter.patch("/:id/decrement-sold", adminOrOrganizerAuth, decrementTicketTypeSoldController);

// 19. Reset tickets sold count back to zero
TicketTypeRouter.patch("/:id/reset-sold", adminAuth, resetTicketTypeSoldController);

export default TicketTypeRouter;